// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrKcCA4NcsIa-ha-4QI02wNlIRxwoFBeU',
    appId: '1:808781166646:web:5c4b5a8feb59440fcb8097',
    messagingSenderId: '808781166646',
    projectId: 'travogenie-74',
    authDomain: 'travogenie-74.firebaseapp.com',
    storageBucket: 'travogenie-74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7beyV3v7T3Cgj0CgTdVCFBaMlhUwVIds',
    appId: '1:808781166646:android:7ba9e0ec85c8d806cb8097',
    messagingSenderId: '808781166646',
    projectId: 'travogenie-74',
    storageBucket: 'travogenie-74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD52KDrdestLnMgyblhJByj_Umq36S6vCY',
    appId: '1:808781166646:ios:d64c94a4eef2d96bcb8097',
    messagingSenderId: '808781166646',
    projectId: 'travogenie-74',
    storageBucket: 'travogenie-74.firebasestorage.app',
    iosBundleId: 'com.example.semMiniproject',
  );
}
