// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBufBVHpEJV45gSQU96GbatnzQK9FXIiVE',
    appId: '1:21179370087:web:4db65c97ff54abc17022c2',
    messagingSenderId: '21179370087',
    projectId: 'jimmy-74',
    authDomain: 'jimmy-74.firebaseapp.com',
    storageBucket: 'jimmy-74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDUBi2xSaw8WzHBlb-f4X_g_ISrRd0Nfs',
    appId: '1:21179370087:android:d5f7138bcfe76f1d7022c2',
    messagingSenderId: '21179370087',
    projectId: 'jimmy-74',
    storageBucket: 'jimmy-74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHCD0SYmdWbIeCftKKkfaaHFWW0bYKaxI',
    appId: '1:21179370087:ios:c2dbbe20260cb24b7022c2',
    messagingSenderId: '21179370087',
    projectId: 'jimmy-74',
    storageBucket: 'jimmy-74.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );
}
