name: todo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.1 
  
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.2   # Ensure you're using the correct version of flutter_launcher_icons

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.jpg 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"