// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5M5duNzBhqNIj6q0K50zANr3Uk_0I4BM',
    appId: '1:1041918340659:web:edc9781fd782a5e1c37d46',
    messagingSenderId: '1041918340659',
    projectId: 'wall-74',
    authDomain: 'wall-74.firebaseapp.com',
    storageBucket: 'wall-74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQDlWKmEcrMElCaQP-FUPfR7d1jV24_oM',
    appId: '1:1041918340659:android:b0466fa8d498a0c8c37d46',
    messagingSenderId: '1041918340659',
    projectId: 'wall-74',
    storageBucket: 'wall-74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVEUvqgzSS32BqGKQS8qO6scTaNnqHfbs',
    appId: '1:1041918340659:ios:e3123bfbbdd2b920c37d46',
    messagingSenderId: '1041918340659',
    projectId: 'wall-74',
    storageBucket: 'wall-74.firebasestorage.app',
    iosBundleId: 'com.example.wall',
  );
}
