// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgm1sgAI52oSk_gFZWgsivRzWHIlER3zw',
    appId: '1:53716473918:android:bc77b554795c749645196f',
    messagingSenderId: '53716473918',
    projectId: 'authenticator-74',
    storageBucket: 'authenticator-74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgcnGbtR9LR0AYB0NxeFqnQYfus5V24SU',
    appId: '1:120287780829:ios:c86feec1f910fa73c72034',
    messagingSenderId: '120287780829',
    projectId: 'notifier-74',
    storageBucket: 'notifier-74.firebasestorage.app',
    iosBundleId: 'com.example.notifier',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcnEC2gkJEzvA5H0RfmllZjiBtSx7RlBs',
    appId: '1:53716473918:web:1ef3149d4684151245196f',
    messagingSenderId: '53716473918',
    projectId: 'authenticator-74',
    authDomain: 'authenticator-74.firebaseapp.com',
    storageBucket: 'authenticator-74.firebasestorage.app',
  );

}