// Platform  Firebase App Id
// web       1:940648559227:web:551be519ee65c062a628de
// android   1:940648559227:android:8195952fbf0dd12ea628de

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7C01px62qsnsG3_I0kZDRNOW7HO9zQzY',
    appId: '1:940648559227:web:551be519ee65c062a628de',
    messagingSenderId: '940648559227',
    projectId: 'crud-74',
    authDomain: 'crud-74.firebaseapp.com',
    storageBucket: 'crud-74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxsuBGQgr-2ZyixZgedg4NVWFKaSxi8rY',
    appId: '1:940648559227:android:8195952fbf0dd12ea628de',
    messagingSenderId: '940648559227',
    projectId: 'crud-74',
    storageBucket: 'crud-74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-TOh-wlKCeU2Aa_QKSR9S5jprbQZovSg',
    appId: '1:940648559227:ios:c57097088adb60afa628de',
    messagingSenderId: '940648559227',
    projectId: 'crud-74',
    storageBucket: 'crud-74.firebasestorage.app',
    androidClientId: '940648559227-nljub4s852s7rnoeviok0ib9h5ql2ped.apps.googleusercontent.com',
    iosClientId: '940648559227-shhu4kj5o0u5veod8gtlcgijqv3k6nle.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfb',
  );

}